# 端口号
server:
  port: 8888
  #  服务请求根路径
  servlet:
    context-path: /demo
# 服务名称
spring:
  application:
    name: springboot-demo
  #    数据源配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
#    扫描Mybatis的xml文件
mybatis:
  mapper-locations: classpath:mapper/*.xml
# 日志打印
logging:
  level:
    com.example.demo.dao: debug
    root: info


